function MINEtypeOfName(name){
	if(name==="mp4"){
		return "video/mp4";
	}else if(name==="ogg"){
		return "video/ogg";
	}else if(name==="webm"){
		return "video/webm";
	}else if(name==="323"){
		return "text/h323";
	}else if(name==="acx"){
		return "application/internet-property-stream";
	}else if(name==="ai"){
		return "application/postscript";
	}else if(name==="aif"){
		return "audio/x-aiff";
	}else if(name==="aifc"){
		return "audio/x-aiff";
	}else  if(name==="aiff"){
		return "audio/x-aiff";
	}else  if(name==="asf"){
		return "video/x-ms-asf";
	}else  if(name==="asr"){
		return "video/x-ms-asf";
	}else  if(name==="asx"){
		return "video/x-ms-asf";
	}else  if(name==="au"){
		return "audio/basic";
	}else  if(name==="avi"){
		return "video/x-msvideo";
	}else  if(name==="axs"){
		return "application/olescript";
	}else if(name==="bas"){
		return "text/plain";
	}else if(name==="bcpio"){
		return "application/x-bcpio";
	}else if(name==="bin"){
		return "application/octet-stream";
	}else if(name==="bmp"){
		return "image/bmp";
	}else if(name==="c"){
		return "text/plain";
	}else if(name==="cat"){
		return "application/vnd.ms-pkiseccat";
	}else if(name==="cdf"){
		return "application/x-cdf";
	}else if(name==="cer"){
		return "application/x-x509-ca-cert";
	}else if(name==="class"){
		return "application/octet-stream";
	}else if(name==="clp"){
		return "application/x-msclip";
	}else if(name==="cmx"){
		return "image/x-cmx";
	}else if(name==="cod"){
		return "image/cis-cod";
	}else if(name==="cpio"){
		return "application/x-cpio";
	}else if(name==="crd"){
		return "application/x-mscardfile";
	}else if(name==="crl"){
		return "application/pkix-crl";
	}else if(name==="crt"){
		return "application/x-x509-ca-cert";
	}else if(name==="csh"){
		return "application/x-csh";
	}else if(name==="css"){
		return "text/css";
	}else if(name==="dcr"){
		return "application/x-director";
	}else if(name==="der"){
		return "application/x-x509-ca-cert";
	}else if(name==="dir"){
		return "application/x-director";
	}else if(name==="dll"){
		return "application/x-msdownload";
	}else if(name==="dms"){
		return "application/octet-stream";
	}else if(name==="doc"){
		return "application/msword";
	}else if(name==="dot"){
		return "application/msword";
	}else if(name==="dvi"){
		return "application/x-dvi";
	}else if(name==="dxr"){
		return "application/x-director";
	}else if(name==="eps"){
		return "application/postscript";
	}else if(name==="etx"){
		return "text/x-setext";
	}else if(name==="evy"){
		return "application/envoy";
	}else if(name==="exe"){
		return "application/octet-stream";
	}else if(name==="fif"){
		return "application/fractals";
	}else if(name==="flr"){
		return "x-world/x-vrml";
	}else if(name==="gif"){
		return "image/gif";
	}else if(name==="gtar"){
		return "application/x-gtar";
	}else if(name==="gz"){
		return "application/x-gzip";
	}else if(name==="h"){
		return "text/plain";
	}else if(name==="hdf"){
		return "application/x-hdf";
	}else if(name==="hlp"){
		return "application/winhlp";
	}else if(name==="hqx"){
		return "application/mac-binhex40";
	}else if(name==="hta"){
		return "application/hta";
	}else if(name==="htc"){
		return "text/x-component";
	}else if(name==="htm"){
		return "text/html";
	}else if(name==="htt"){
		return "text/webviewhtml";
	}else if(name==="ico"){
		return "image/x-icon";
	}else if(name==="ief"){
		return "image/ief";
	}else if(name==="iii"){
		return "application/x-iphone";
	}else if(name==="ins"){
		return "application/x-internet-signup";
	}else if(name==="isp"){
		return "application/x-internet-signup";
	}else if(name==="jfif"){
		return "image/pipeg";
	}else if(name==="jpe"){
		return "image/jpeg";
	}else if(name==="jpeg"){
		return "image/jpeg";
	}else if(name==="jpg"){
		return "image/jpeg";
	}else if(name==="js"){
		return "application/x-javascript";
	}else if(name==="latex"){
		return "application/x-latex";
	}else if(name==="lha"){
		return "application/octet-stream";
	}else if(name==="lsf"){
		return "video/x-la-asf";
	}else if(name==="lsx"){
		return "video/x-la-asf";
	}else if(name==="lzh"){
		return "application/octet-stream";
	}else if(name==="m13"){
		return "application/x-msmediaview";
	}else if(name==="m14"){
		return "application/x-msmediaview";
	}else if(name==="m3u"){
		return "audio/x-mpegurl";
	}else if(name==="man"){
		return "application/x-troff-man";
	}else if(name==="mdb"){
		return "application/x-msaccess";
	}else if(name==="me"){
		return "application/x-troff-me";
	}else if(name==="mht"){
		return "message/rfc822";
	}else if(name==="mhtml"){
		return "message/rfc822";
	}else if(name==="mid"){
		return "audio/mid";
	}else if(name==="mny"){
		return "application/x-msmoney";
	}else if(name==="mov"){
		return "video/quicktime";
	}else if(name==="movie"){
		return "video/x-sgi-movie";
	}else if(name==="mp2"){
		return "video/mpeg";
	}else if(name==="mp3"){
		return "video/mpeg";
	}else if(name==="mpa"){
		return "video/mpeg";
	}else if(name==="mpe"){
		return "video/mpeg";
	}else if(name==="mpeg"){
		return "video/mpeg";
	}else if(name==="mpg"){
		return "video/mpeg";
	}else if(name==="mpp"){
		return "application/vnd.ms-project";
	}else if(name==="mpv2"){
		return "video/mpeg";
	}else if(name==="ms"){
		return "application/x-troff-ms";
	}else if(name==="mvb"){
		return "application/x-msmediaview";
	}else if(name==="nws"){
		return "message/rfc822";
	}else if(name==="oda"){
		return "application/oda";
	}else if(name==="p10"){
		return "application/pkcs10";
	}else if(name==="p12"){
		return "application/x-pkcs12";
	}else if(name==="p7b"){
		return "application/x-pkcs7-certificates";
	}else if(name==="p7c"){
		return "application/x-pkcs7-mime";
	}else if(name==="p7m"){
		return "application/x-pkcs7-mime";
	}else if(name==="p7r"){
		return "application/x-pkcs7-certreqresp";
	}else if(name==="p7s"){
		return "application/x-pkcs7-signature";
	}else if(name==="pbm"){
		return "image/x-portable-bitmap";
	}else if(name==="pdf"){
		return "application/pdf";
	}else if(name==="pfx"){
		return "application/x-pkcs12";
	}else if(name==="pgm"){
		return "image/x-portable-graymap";
	}else if(name==="pko"){
		return "application/ynd.ms-pkipko";
	}else if(name==="pma"){
		return "application/x-perfmon";
	}else if(name==="pmc"){
		return "application/x-perfmon";
	}else if(name==="pml"){
		return "application/x-perfmon";
	}else if(name==="pmr"){
		return "application/x-perfmon";
	}else if(name==="pmw"){
		return "application/x-perfmon";
	}else if(name==="pnm"){
		return "image/x-portable-anymap";
	}else if(name==="pot"){
		return "application/vnd.ms-powerpoint";
	}else if(name==="ppm"){
		return "image/x-portable-pixmap";
	}else if(name==="pps"){
		return "application/vnd.ms-powerpoint";
	}else if(name==="ppt"){
		return "application/vnd.ms-powerpoint";
	}else if(name==="prf"){
		return "application/pics-rules";
	}else if(name==="ps"){
		return "application/postscript";
	}else if(name==="pub"){
		return "application/x-mspublisher";
	}else if(name==="qt"){
		return "video/quicktime";
	}else if(name==="ra"){
		return "audio/x-pn-realaudio";
	}else if(name==="ram"){
		return "audio/x-pn-realaudio";
	}else if(name==="ras"){
		return "image/x-cmu-raster";
	}else if(name==="rgb"){
		return "image/x-rgb";
	}else if(name==="rmi"){
		return "audio/mid http://www.dreamdu.com";
	}else if(name==="roff"){
		return "application/x-troff";
	}else if(name==="rtf"){
		return "application/rtf";
	}else if(name==="rtx"){
		return "text/richtext";
	}else if(name==="scd"){
		return "application/x-msschedule";
	}else if(name==="sct"){
		return "text/scriptlet";
	}else if(name==="setpay"){
		return "application/set-payment-initiation";
	}else if(name==="setreg"){
		return "application/set-registration-initiation";
	}else if(name==="sh"){
		return "application/x-sh";
	}else if(name==="shar"){
		return "application/x-shar";
	}else if(name==="sit"){
		return "application/x-stuffit";
	}else if(name==="snd"){
		return "audio/basic";
	}else if(name==="spc"){
		return "application/x-pkcs7-certificates";
	}else if(name==="spl"){
		return "application/futuresplash";
	}else if(name==="src"){
		return "application/x-wais-source";
	}else if(name==="sst"){
		return "application/vnd.ms-pkicertstore";
	}else if(name==="stl"){
		return "application/vnd.ms-pkistl";
	}else if(name==="stm"){
		return "text/html";
	}else if(name==="svg"){
		return "image/svg+xml";
	}else if(name==="sv4cpio"){
		return "application/x-sv4cpio";
	}else if(name==="sv4crc"){
		return "application/x-sv4crc";
	}else if(name==="swf"){
		return "application/x-shockwave-flash";
	}else if(name==="t"){
		return "application/x-troff";
	}else if(name==="tar"){
		return "application/x-tar";
	}else if(name==="tcl"){
		return "application/x-tcl";
	}else if(name==="tex"){
		return "application/x-tex";
	}else if(name==="texi"){
		return "application/x-texinfo";
	}else if(name==="texinfo"){
		return "application/x-texinfo";
	}else if(name==="tgz"){
		return "application/x-compressed";
	}else if(name==="tif"){
		return "image/tiff";
	}else if(name==="tiff"){
		return "image/tiff";
	}else if(name==="tr"){
		return "application/x-troff";
	}else if(name==="trm"){
		return "application/x-msterminal";
	}else if(name==="tsv"){
		return "text/tab-separated-values";
	}else if(name==="txt"){
		return "text/plain";
	}else if(name==="uls"){
		return "text/iuls";
	}else if(name==="ustar"){
		return "application/x-ustar";
	}else if(name==="vcf"){
		return "text/x-vcard";
	}else if(name==="vrml"){
		return "x-world/x-vrml";
	}else if(name==="wav"){
		return "audio/x-wav";
	}else if(name==="wcm"){
		return "application/vnd.ms-works";
	}else if(name==="wdb"){
		return "application/vnd.ms-works";
	}else if(name==="wks"){
		return "application/vnd.ms-works";
	}else if(name==="wmf"){
		return "application/x-msmetafile";
	}else if(name==="wps"){
		return "application/vnd.ms-works";
	}else if(name==="wri"){
		return "application/x-mswrite";
	}else if(name==="wrl"){
		return "x-world/x-vrml";
	}else if(name==="wrz"){
		return "x-world/x-vrml";
	}else if(name==="xaf"){
		return "x-world/x-vrml";
	}else if(name==="xbm"){
		return "image/x-xbitmap";
	}else if(name==="xla"){
		return "application/vnd.ms-excel";
	}else if(name==="xlc"){
		return "application/vnd.ms-excel";
	}else if(name==="xlm"){
		return "application/vnd.ms-excel";
	}else if(name==="xls"){
		return "application/vnd.ms-excel";
	}else if(name==="xlt"){
		return "application/vnd.ms-excel";
	}else if(name==="xlw"){
		return "application/vnd.ms-excel";
	}else if(name==="xof"){
		return "x-world/x-vrml";
	}else if(name==="xpm"){
		return "image/x-xpixmap";
	}else if(name==="xwd"){
		return "image/x-xwindowdump";
	}else if(name==="z"){
		return "application/x-compress";
	}else if(name==="zip"){
		return "application/zip";
	}else if(name==="*"){
		return "application/octet-stream";
	}else if(name===""){
		return "application/octet-stream";
	}
    return "";
}